#!/usr/bin/ruby

command=`ps U jenkins | grep jenkins.war |wc -l`
exit_value=3

if command.strip == "1"
	puts "Jenkins is running"
	exit_value=0
else
	puts "Jenkins has stopped"
	exit_value=2
end

exit exit_value
