#!/usr/bin/ruby

command=`ps U jenkins | grep jenkins.war |wc -l`
exit_value=3

if command.strip != "0"
	puts "Jenkins is running | status=1"
	exit_value=0
else
	puts "Jenkins has stopped | status=0"
	exit_value=2
end

exit exit_value
